import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');

  useEffect(() => {
    const saved = localStorage.getItem('toka-lang');
    if (saved) setLang(saved);
  }, []);

  useEffect(() => {
    localStorage.setItem('toka-lang', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const toggleLang = () => setLang((prev) => (prev === 'en' ? 'ar' : 'en'));

  // Helper: get text with fallback
  const t = (textAr, textEn) => {
    if (lang === 'ar') return textAr || textEn || '';
    return textEn || textAr || '';
  };

  // UI translations
  const translations = {
    en: {
      home: 'Home',
      products: 'Products',
      about: 'About',
      cart: 'Cart',
      search: 'Search products...',
      addToCart: 'Add to Cart',
      buyNow: 'Buy Now',
      checkout: 'Checkout',
      orderViaWhatsApp: 'Order via WhatsApp',
      featuredProducts: 'Featured Products',
      bestSellers: 'Best Sellers',
      allProducts: 'All Products',
      categories: 'Categories',
      allCategories: 'All Categories',
      price: 'Price',
      egp: 'EGP',
      inStock: 'In Stock',
      outOfStock: 'Out of Stock',
      total: 'Total',
      subtotal: 'Subtotal',
      yourCart: 'Your Cart',
      emptyCart: 'Your cart is empty',
      continueShopping: 'Continue Shopping',
      proceedToCheckout: 'Proceed to Checkout',
      name: 'Name',
      phone: 'Phone',
      address: 'Address',
      email: 'Email (optional)',
      notes: 'Notes (optional)',
      placeOrder: 'Place Order',
      cashOnDelivery: 'Cash on Delivery',
      orderSuccess: 'Order Placed Successfully!',
      orderSuccessMsg: 'Thank you for your order! We will contact you soon.',
      backToHome: 'Back to Home',
      qty: 'Qty',
      remove: 'Remove',
      noProducts: 'No products found',
      loading: 'Loading...',
      viewAll: 'View All',
      shopNow: 'Shop Now',
      heroTitle: 'Tooka — Handmade Headbands',
      heroSubtitle: 'Premium Quality | Unique Designs | For Babies, Girls & Women | Made with Care | Shipping Inside & Outside Egypt',
      adminLogin: 'Admin Login',
      username: 'Username',
      password: 'Password',
      login: 'Login',
      dashboard: 'Dashboard',
      logout: 'Logout',
      totalOrders: 'Total Orders',
      ordersToday: 'Orders Today',
      totalProducts: 'Total Products',
      estimatedRevenue: 'Est. Revenue',
      sendDailyReport: 'Send Daily Report',
      orderStatus: 'Status',
      pending: 'Pending',
      shipped: 'Shipped',
      delivered: 'Delivered',
      canceled: 'Canceled',
      actions: 'Actions',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      create: 'Create',
      addProduct: 'Add Product',
      addCategory: 'Add Category',
      editAbout: 'Edit About Page',
      manageProducts: 'Manage Products',
      manageCategories: 'Manage Categories',
      manageOrders: 'Manage Orders',
      pages: 'Pages',
      featured: 'Featured',
      stock: 'Stock',
      category: 'Category',
      images: 'Images',
      description: 'Description',
      items: 'Items',
      date: 'Date',
      customer: 'Customer',
      // Track Order
      trackOrder: 'Track Order',
      trackYourOrder: 'Track Your Order',
      trackOrderDesc: 'Enter your Order ID and phone number to check your order status',
      orderId: 'Order ID',
      orderIdHint: 'You can find this in your order confirmation email',
      phoneNumber: 'Phone Number',
      searching: 'Searching...',
      orderNotFound: 'Order not found. Please check your Order ID and phone number.',
      currentStatus: 'Current Status',
      orderPlaced: 'Order Placed',
      // Checkout
      shippingInfo: 'Shipping Information',
      paymentMethod: 'Payment Method',
      payWhenReceive: 'Pay when you receive your order',
      processing: 'Processing...',
      orderSummary: 'Order Summary',
      couponCode: 'Coupon Code',
      apply: 'Apply',
      discount: 'Discount',
      fillRequired: 'Please fill in all required fields',
      cartEmpty: 'Cart is empty',
      invalidCoupon: 'Invalid coupon',
      // Order Success
      yourOrderId: 'Your Order ID',
      saveOrderId: 'Save this ID to track your order status anytime.',
      trackMyOrder: 'Track My Order',
      // Wishlist
      wishlist: 'My Wishlist',
      itemsSaved: 'items saved',
      emptyWishlist: 'Your wishlist is empty',
      browseWishlistHint: 'Browse products and tap the heart to save them here',
      browseProducts: 'Browse Products',
      add: 'Add',
      // Cart
      emptyCartHint: 'Looks like you haven\'t added anything yet.',
      // Homepage
      newCollection: 'NEW COLLECTION',
      heroMainTitle: 'Handmade Accessories for',
      heroHighlight: 'Little Princesses',
      heroDesc: 'Beautiful handmade headbands made with love. Perfect unique accessories to celebrate your little one\'s everyday moments.',
      shopCollection: 'Shop Collection',
      viewBestSellers: 'View Best Sellers',
      handmade: 'Handmade',
      secure: 'Secure',
      fastDelivery: 'Fast Delivery',
      shopByCategory: 'Shop by Category',
      bestSellersTitle: 'Best Sellers 💕',
      viewAllProducts: 'View All Products',
      promoTitle: 'Free Gift with Orders Over 500 EGP 🎁',
      handmadeWithLove: 'Handmade with Love 💖',
      handmadeWithLoveDesc: 'Every single piece is cut, sewn, and assembled by hand in our studio. We use only the softest fabrics sourced carefully to ensure the absolute best quality for your little ones.',
      readOurStory: 'Read Our Story',
      joinFamily: 'Join the TOOKA Family',
      joinFamilyDesc: 'Subscribe to get special offers, free giveaways, and once-in-a-lifetime deals.',
      enterEmail: 'Enter your email',
      subscribe: 'Subscribe',
      // Footer
      quickLinks: 'Quick Links',
      contactUs: 'Contact Us',
      joinNewsletter: 'Join Our Newsletter',
      newsletterHint: 'Subscribe for updates and exclusive offers!',
      yourEmail: 'Your email address',
      allRights: 'All rights reserved.',
      footerDesc: 'Beautiful handmade headbands made with love. Perfect accessories for your little princesses.',
      // About
      ourStory: 'Our Story',
      noContent: 'No content available.',
      handcraftedDetail: 'Handcrafted with precise details & love.',
      // Product Features
      featureFastDelivery: 'Fast Delivery',
      featureFastDeliveryDesc: 'Inside & outside Egypt',
      featurePremiumQuality: 'Premium Quality',
      featurePremiumQualityDesc: '100% handmade',
      featureMadeWithLove: 'Made with Love',
      featureMadeWithLoveDesc: 'Care in every detail',
      featureEasyReturns: 'Easy Returns',
      featureEasyReturnsDesc: '14-day return policy',
      // Shipping
      governorate: 'Governorate',
      area: 'Area',
      selectGovernorate: 'Select Governorate',
      selectArea: 'Select Area',
      shipping: 'Shipping',
      free: 'Free',
      addressDetails: 'Street, building, floor...',
      // Admin — Shipping
      shippingZones: 'Shipping Zones',
      governorates: 'governorates',
      addGovernorate: '+ Add Governorate',
      governorateName: 'Governorate Name',
      areas: 'areas',
      customerPrice: 'Customer Price',
      actualCost: 'Actual Cost',
      profit: 'Profit',
      newArea: 'New Area',
      // Admin — Profit
      profitCenter: 'Profit Center',
      overview: 'Overview',
      offlineSales: 'Offline Sales',
      expensesLabel: 'Expenses',
      allTransactions: 'All Transactions',
      today: 'Today',
      thisWeek: 'This Week',
      thisMonth: 'This Month',
      allTime: 'All Time',
      netProfit: 'Net Profit',
      grossProfit: 'Gross Profit',
      totalRevenue: 'Total Revenue',
      totalCost: 'Total Cost',
      onlineOrders: 'Online Orders',
      shippingProfit: 'Shipping Profit',
      chargedToCustomers: 'Charged to Customers',
      productProfit: 'Product Profit',
      calculation: 'Calculation',
      onlineProductProfit: 'Online Product Profit',
      offlineProfit: 'Offline Profit',
      recordOfflineSale: 'Record Offline Sale',
      product: 'Product',
      selectOrType: '-- Select or type below --',
      productName: 'Product Name',
      quantity: 'Quantity',
      sellPrice: 'Sell Price (per unit)',
      costPriceLabel: 'Cost Price (per unit)',
      deductFromStock: 'Deduct from stock',
      recordSale: 'Record Sale',
      noOfflineSales: 'No offline sales recorded',
      stockDeducted: 'Stock deducted',
      addExpense: 'Add Expense',
      expenseDesc: 'Description',
      amount: 'Amount',
      expenseCategory: 'Category',
      catGeneral: 'General',
      catMaterials: 'Materials',
      catRent: 'Rent',
      catTools: 'Tools',
      catMarketing: 'Marketing',
      catShipping: 'Shipping',
      catOther: 'Other',
      noExpenses: 'No expenses recorded',
      latestTransactions: 'All Transactions (Latest 50)',
      type: 'Type',
      online: 'Online',
      offline: 'Offline',
      revenue: 'Revenue',
      cost: 'Cost',
      itemsSold: 'Items Sold',
      orders: 'Orders',
      sales: 'Sales',
      // Admin — Dashboard
      welcomeBack: 'Welcome back!',
      storeToday: "Here's what's happening with your store today.",
      sendReport: 'Send Daily Report',
      downloadBackup: 'Download Backup',
      contactInfo: 'Contact Info',
      contactInfoDesc: 'Email & phone shown on the website footer',
      changePassword: 'Change Password',
      changePasswordDesc: 'Update your admin login password',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm',
      saving: 'Saving...',
      delText: 'Del',
      deleteConfirm: 'Delete?',
      coupons: 'Coupons',
      reviews: 'Reviews',
      profitNav: 'Profit',
      shippingNav: 'Shipping',
      skuSearch: 'SKU Search',
      justBought: 'bought',
      minutesAgo: 'min ago',
      hoursAgo: 'hr ago',
      // Admin — Settings
      settings: 'Settings',
      featureFlags: 'Feature Flags',
      flashSalesLabel: 'Flash Sales',
      bundlesLabel: 'Bundle Deals',
      socialProofLabel: 'Social Proof Popup',
      giftWrapLabel: 'Gift Wrapping',
      customerDbLabel: 'Customer Database',
      giftWrapPrice: 'Gift Wrap Price (EGP)',
      enabled: 'Enabled',
      disabled: 'Disabled',
      // Admin — Customers
      customers: 'Customers',
      totalSpent: 'Total Spent',
      lastOrder: 'Last Order',
      orderCount: 'Order Count',
      noCustomers: 'No customers found',
      // Admin — Flash Sales
      createFlashSale: 'Create Flash Sale',
      discountedPrice: 'Discounted Price',
      startTime: 'Start Time',
      endTime: 'End Time',
      originalPrice: 'Original Price',
      active: 'Active',
      expired: 'Expired',
      upcoming: 'Upcoming',
      noFlashSales: 'No flash sales',
      // Admin — Bundles
      createBundle: 'Create Bundle',
      bundlePrice: 'Bundle Price',
      youSave: 'You Save',
      selectProducts: 'Select Products',
      noBundles: 'No bundles',
      productsInBundle: 'Products in Bundle',
      // Checkout
      giftWrapping: 'Gift Wrapping',
      giftWrapDesc: "We'll wrap your order beautifully",
    },
    ar: {
      home: 'الرئيسية',
      products: 'المنتجات',
      about: 'عن توكا',
      cart: 'السلة',
      search: 'ابحثي عن منتج...',
      addToCart: 'أضف للسلة',
      buyNow: 'اشتري الآن',
      checkout: 'إتمام الطلب',
      orderViaWhatsApp: 'اطلبي عبر واتساب',
      featuredProducts: 'منتجات مميزة',
      bestSellers: 'الأكثر مبيعاً',
      allProducts: 'كل المنتجات',
      categories: 'الأقسام',
      allCategories: 'كل الأقسام',
      price: 'السعر',
      egp: 'ج.م',
      inStock: 'متوفر',
      outOfStock: 'نفذ',
      total: 'الإجمالي',
      subtotal: 'المجموع',
      yourCart: 'سلة التسوق',
      emptyCart: 'سلتك فارغة',
      continueShopping: 'تابعي التسوق',
      proceedToCheckout: 'إتمام الطلب',
      name: 'الاسم',
      phone: 'الهاتف',
      address: 'العنوان',
      email: 'البريد الإلكتروني (اختياري)',
      notes: 'ملاحظات (اختياري)',
      placeOrder: 'تأكيد الطلب',
      cashOnDelivery: 'الدفع عند الاستلام',
      orderSuccess: 'تم الطلب بنجاح!',
      orderSuccessMsg: 'شكراً لطلبك! سنتواصل معك قريباً.',
      backToHome: 'العودة للرئيسية',
      qty: 'الكمية',
      remove: 'حذف',
      noProducts: 'لا توجد منتجات',
      loading: 'جاري التحميل...',
      viewAll: 'عرض الكل',
      shopNow: 'تسوقي الآن',
      heroTitle: 'توكا — توك يدوية',
      heroSubtitle: 'جودة عالية | تصاميم فريدة | للبنات والسيدات | صناعة يدوية بعناية | شحن داخل وخارج مصر',
      adminLogin: 'تسجيل دخول الأدمن',
      username: 'اسم المستخدم',
      password: 'كلمة المرور',
      login: 'دخول',
      dashboard: 'لوحة التحكم',
      logout: 'خروج',
      totalOrders: 'إجمالي الطلبات',
      ordersToday: 'طلبات اليوم',
      totalProducts: 'إجمالي المنتجات',
      estimatedRevenue: 'الإيرادات المتوقعة',
      sendDailyReport: 'إرسال التقرير اليومي',
      orderStatus: 'الحالة',
      pending: 'قيد الانتظار',
      shipped: 'تم الشحن',
      delivered: 'تم التوصيل',
      canceled: 'ملغي',
      actions: 'إجراءات',
      save: 'حفظ',
      cancel: 'إلغاء',
      delete: 'حذف',
      edit: 'تعديل',
      create: 'إنشاء',
      addProduct: 'إضافة منتج',
      addCategory: 'إضافة قسم',
      editAbout: 'تعديل صفحة عن',
      manageProducts: 'إدارة المنتجات',
      manageCategories: 'إدارة الأقسام',
      manageOrders: 'إدارة الطلبات',
      pages: 'الصفحات',
      featured: 'مميز',
      stock: 'المخزون',
      category: 'القسم',
      images: 'صور',
      description: 'الوصف',
      items: 'العناصر',
      date: 'التاريخ',
      customer: 'العميل',
      // Track Order
      trackOrder: 'تتبع الطلب',
      trackYourOrder: 'تتبع طلبك',
      trackOrderDesc: 'أدخل رقم الطلب ورقم الهاتف للتحقق من حالة طلبك',
      orderId: 'رقم الطلب',
      orderIdHint: 'يمكنك إيجاده في رسالة تأكيد الطلب',
      phoneNumber: 'رقم الهاتف',
      searching: 'جاري البحث...',
      orderNotFound: 'لم يتم العثور على الطلب. تأكد من رقم الطلب ورقم الهاتف.',
      currentStatus: 'الحالة الحالية',
      orderPlaced: 'تم تقديم الطلب',
      // Checkout
      shippingInfo: 'معلومات الشحن',
      paymentMethod: 'طريقة الدفع',
      payWhenReceive: 'الدفع عند استلام الطلب',
      processing: 'جاري المعالجة...',
      orderSummary: 'ملخص الطلب',
      couponCode: 'كود الخصم',
      apply: 'تطبيق',
      discount: 'الخصم',
      fillRequired: 'يرجى ملء جميع الحقول المطلوبة',
      cartEmpty: 'السلة فارغة',
      invalidCoupon: 'كود خصم غير صالح',
      // Order Success
      yourOrderId: 'رقم طلبك',
      saveOrderId: 'احفظ هذا الرقم لتتبع حالة طلبك في أي وقت.',
      trackMyOrder: 'تتبع طلبي',
      // Wishlist
      wishlist: 'المفضلة',
      itemsSaved: 'عناصر محفوظة',
      emptyWishlist: 'قائمة المفضلة فارغة',
      browseWishlistHint: 'تصفحي المنتجات واضغطي على القلب لحفظها هنا',
      browseProducts: 'تصفح المنتجات',
      add: 'أضف',
      // Cart
      emptyCartHint: 'يبدو أنك لم تضيفي أي شيء بعد.',
      // Homepage
      newCollection: 'مجموعة جديدة',
      heroMainTitle: 'إكسسوارات يدوية لـ',
      heroHighlight: 'الأميرات الصغيرات',
      heroDesc: 'توك يدوية جميلة مصنوعة بحب. إكسسوارات فريدة ومثالية للاحتفال بلحظات صغيرتك اليومية.',
      shopCollection: 'تسوقي المجموعة',
      viewBestSellers: 'الأكثر مبيعاً',
      handmade: 'صناعة يدوية',
      secure: 'آمن',
      fastDelivery: 'توصيل سريع',
      shopByCategory: 'تسوقي حسب القسم',
      bestSellersTitle: 'الأكثر مبيعاً 💕',
      viewAllProducts: 'عرض كل المنتجات',
      promoTitle: 'هدية مجانية مع الطلبات فوق 500 جنيه 🎁',
      handmadeWithLove: 'صناعة يدوية بحب 💖',
      handmadeWithLoveDesc: 'كل قطعة يتم قصها وخياطتها وتجميعها يدوياً في ورشتنا. نستخدم فقط أنعم الأقمشة المختارة بعناية لضمان أفضل جودة لصغيراتك.',
      readOurStory: 'اقرئي قصتنا',
      joinFamily: 'انضمي لعائلة توكا',
      joinFamilyDesc: 'اشتركي للحصول على عروض خاصة وهدايا مجانية وعروض لا تتكرر.',
      enterEmail: 'أدخلي بريدك الإلكتروني',
      subscribe: 'اشتراك',
      // Footer
      quickLinks: 'روابط سريعة',
      contactUs: 'تواصلي معنا',
      joinNewsletter: 'انضمي للنشرة البريدية',
      newsletterHint: 'اشتركي للحصول على التحديثات والعروض الحصرية!',
      yourEmail: 'بريدك الإلكتروني',
      allRights: 'جميع الحقوق محفوظة.',
      footerDesc: 'توك يدوية جميلة مصنوعة بحب. إكسسوارات مثالية لأميراتك الصغيرات.',
      // About
      ourStory: 'قصتنا',
      noContent: 'لا يوجد محتوى متاح.',
      handcraftedDetail: 'مصنوعة يدوياً بتفاصيل دقيقة وحب.',
      // Product Features
      featureFastDelivery: 'توصيل سريع',
      featureFastDeliveryDesc: 'داخل وخارج مصر',
      featurePremiumQuality: 'جودة عالية',
      featurePremiumQualityDesc: '100% صناعة يدوية',
      featureMadeWithLove: 'صُنع بحب',
      featureMadeWithLoveDesc: 'عناية في كل تفصيلة',
      featureEasyReturns: 'استرجاع سهل',
      featureEasyReturnsDesc: 'سياسة استرجاع 14 يوم',
      // Shipping
      governorate: 'المحافظة',
      area: 'المنطقة',
      selectGovernorate: 'اختر المحافظة',
      selectArea: 'اختر المنطقة',
      shipping: 'الشحن',
      free: 'مجاناً',
      addressDetails: 'الشارع، المبنى، الطابق...',
      // Admin — Shipping
      shippingZones: 'مناطق الشحن',
      governorates: 'محافظات',
      addGovernorate: '+ إضافة محافظة',
      governorateName: 'اسم المحافظة',
      areas: 'مناطق',
      customerPrice: 'سعر العميل',
      actualCost: 'التكلفة الفعلية',
      profit: 'الربح',
      newArea: 'منطقة جديدة',
      // Admin — Profit
      profitCenter: 'مركز الأرباح',
      overview: 'نظرة عامة',
      offlineSales: 'مبيعات أوفلاين',
      expensesLabel: 'المصاريف',
      allTransactions: 'كل العمليات',
      today: 'اليوم',
      thisWeek: 'هذا الأسبوع',
      thisMonth: 'هذا الشهر',
      allTime: 'الكل',
      netProfit: 'صافي الربح',
      grossProfit: 'إجمالي الربح',
      totalRevenue: 'إجمالي الإيرادات',
      totalCost: 'إجمالي التكلفة',
      onlineOrders: 'طلبات أونلاين',
      shippingProfit: 'ربح الشحن',
      chargedToCustomers: 'المحصّل من العملاء',
      productProfit: 'ربح المنتجات',
      calculation: 'الحساب',
      onlineProductProfit: 'ربح منتجات أونلاين',
      offlineProfit: 'ربح أوفلاين',
      recordOfflineSale: 'تسجيل بيع أوفلاين',
      product: 'المنتج',
      selectOrType: '-- اختر أو اكتب بالأسفل --',
      productName: 'اسم المنتج',
      quantity: 'الكمية',
      sellPrice: 'سعر البيع (للوحدة)',
      costPriceLabel: 'سعر التكلفة (للوحدة)',
      deductFromStock: 'خصم من المخزون',
      recordSale: 'تسجيل البيع',
      noOfflineSales: 'لا توجد مبيعات أوفلاين',
      stockDeducted: 'تم الخصم من المخزون',
      addExpense: 'إضافة مصروف',
      expenseDesc: 'الوصف',
      amount: 'المبلغ',
      expenseCategory: 'التصنيف',
      catGeneral: 'عام',
      catMaterials: 'خامات',
      catRent: 'إيجار',
      catTools: 'أدوات',
      catMarketing: 'تسويق',
      catShipping: 'شحن',
      catOther: 'أخرى',
      noExpenses: 'لا توجد مصاريف',
      latestTransactions: 'كل العمليات (آخر 50)',
      type: 'النوع',
      online: 'أونلاين',
      offline: 'أوفلاين',
      revenue: 'الإيرادات',
      cost: 'التكلفة',
      itemsSold: 'قطع مباعة',
      orders: 'الطلبات',
      sales: 'المبيعات',
      // Admin — Dashboard
      welcomeBack: 'أهلاً بعودتك!',
      storeToday: 'إليك ما يحدث في متجرك اليوم.',
      sendReport: 'إرسال التقرير اليومي',
      downloadBackup: 'تحميل النسخة الاحتياطية',
      contactInfo: 'معلومات التواصل',
      contactInfoDesc: 'الإيميل والرقم اللي بيظهروا في الموقع',
      changePassword: 'تغيير كلمة المرور',
      changePasswordDesc: 'تحديث كلمة مرور الأدمن',
      currentPassword: 'كلمة المرور الحالية',
      newPassword: 'كلمة المرور الجديدة',
      confirmPassword: 'تأكيد',
      saving: 'جاري الحفظ...',
      delText: 'حذف',
      deleteConfirm: 'حذف؟',
      coupons: 'الكوبونات',
      reviews: 'التقييمات',
      profitNav: 'الأرباح',
      shippingNav: 'الشحن',
      skuSearch: 'بحث SKU',
      justBought: 'اشترى',
      minutesAgo: 'دقيقة',
      hoursAgo: 'ساعة',
      // Admin — Settings
      settings: 'الإعدادات',
      featureFlags: 'التحكم في المميزات',
      flashSalesLabel: 'عروض وقتية',
      bundlesLabel: 'باقات',
      socialProofLabel: 'إشعارات الشراء',
      giftWrapLabel: 'تغليف هدايا',
      customerDbLabel: 'قاعدة العملاء',
      giftWrapPrice: 'سعر تغليف الهدايا (جنيه)',
      enabled: 'مفعّل',
      disabled: 'متوقف',
      // Admin — Customers
      customers: 'العملاء',
      totalSpent: 'إجمالي المشتريات',
      lastOrder: 'آخر طلب',
      orderCount: 'عدد الطلبات',
      noCustomers: 'لا يوجد عملاء',
      // Admin — Flash Sales
      createFlashSale: 'إنشاء عرض وقتي',
      discountedPrice: 'السعر بعد الخصم',
      startTime: 'وقت البداية',
      endTime: 'وقت النهاية',
      originalPrice: 'السعر الأصلي',
      active: 'نشط',
      expired: 'منتهي',
      upcoming: 'قادم',
      noFlashSales: 'لا توجد عروض',
      // Admin — Bundles
      createBundle: 'إنشاء باقة',
      bundlePrice: 'سعر الباقة',
      youSave: 'توفر',
      selectProducts: 'اختر المنتجات',
      noBundles: 'لا توجد باقات',
      productsInBundle: 'منتجات الباقة',
      // Checkout
      giftWrapping: 'تغليف هدايا',
      giftWrapDesc: 'هنغلف طلبك بشكل جميل',
    },
  };

  const ui = translations[lang] || translations.en;

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t, ui }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);
