require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('./config/db');
const ShippingZone = require('./models/ShippingZone');

const egyptGovernorates = [
  {
    governorate: 'القاهرة',
    areas: [
      { name: 'مدينة نصر', cost: 0 },
      { name: 'مصر الجديدة', cost: 0 },
      { name: 'المعادي', cost: 0 },
      { name: 'التجمع الخامس', cost: 0 },
      { name: 'الرحاب', cost: 0 },
      { name: 'مدينتي', cost: 0 },
      { name: 'الشروق', cost: 0 },
      { name: 'العبور', cost: 0 },
      { name: 'حلوان', cost: 0 },
      { name: 'المقطم', cost: 0 },
      { name: 'شبرا', cost: 0 },
      { name: 'عين شمس', cost: 0 },
      { name: 'المطرية', cost: 0 },
      { name: 'الزيتون', cost: 0 },
      { name: 'حدائق القبة', cost: 0 },
      { name: 'روكسي', cost: 0 },
      { name: 'العباسية', cost: 0 },
      { name: 'وسط البلد', cost: 0 },
      { name: 'الدرب الأحمر', cost: 0 },
      { name: 'السيدة زينب', cost: 0 },
      { name: 'بولاق', cost: 0 },
      { name: 'الزمالك', cost: 0 },
      { name: 'جاردن سيتي', cost: 0 },
      { name: 'المنيل', cost: 0 },
      { name: 'التبين', cost: 0 },
      { name: 'بدر', cost: 0 },
      { name: '15 مايو', cost: 0 },
    ],
  },
  {
    governorate: 'الجيزة',
    areas: [
      { name: 'الدقي', cost: 0 },
      { name: 'المهندسين', cost: 0 },
      { name: 'العجوزة', cost: 0 },
      { name: 'فيصل', cost: 0 },
      { name: 'الهرم', cost: 0 },
      { name: 'حدائق الأهرام', cost: 0 },
      { name: '6 أكتوبر', cost: 0 },
      { name: 'الشيخ زايد', cost: 0 },
      { name: 'بيفرلي هيلز', cost: 0 },
      { name: 'دريم لاند', cost: 0 },
      { name: 'أبو رواش', cost: 0 },
      { name: 'كرداسة', cost: 0 },
      { name: 'البدرشين', cost: 0 },
      { name: 'الحوامدية', cost: 0 },
      { name: 'العياط', cost: 0 },
      { name: 'أطفيح', cost: 0 },
      { name: 'الصف', cost: 0 },
      { name: 'أوسيم', cost: 0 },
      { name: 'منشأة القناطر', cost: 0 },
      { name: 'ابو النمرس', cost: 0 },
      { name: 'الوراق', cost: 0 },
      { name: 'إمبابة', cost: 0 },
      { name: 'بولاق الدكرور', cost: 0 },
    ],
  },
  {
    governorate: 'الإسكندرية',
    areas: [
      { name: 'سموحة', cost: 0 },
      { name: 'سيدي جابر', cost: 0 },
      { name: 'كليوباترا', cost: 0 },
      { name: 'ستانلي', cost: 0 },
      { name: 'جليم', cost: 0 },
      { name: 'سان ستيفانو', cost: 0 },
      { name: 'المنتزه', cost: 0 },
      { name: 'المعمورة', cost: 0 },
      { name: 'العصافرة', cost: 0 },
      { name: 'أبو قير', cost: 0 },
      { name: 'المندرة', cost: 0 },
      { name: 'ميامي', cost: 0 },
      { name: 'سيدي بشر', cost: 0 },
      { name: 'لوران', cost: 0 },
      { name: 'بحري', cost: 0 },
      { name: 'المنشية', cost: 0 },
      { name: 'كرموز', cost: 0 },
      { name: 'العطارين', cost: 0 },
      { name: 'محرم بك', cost: 0 },
      { name: 'الإبراهيمية', cost: 0 },
      { name: 'العامرية', cost: 0 },
      { name: 'برج العرب', cost: 0 },
      { name: 'كينج مريوط', cost: 0 },
      { name: 'الدخيلة', cost: 0 },
      { name: 'العجمي', cost: 0 },
      { name: 'البيطاش', cost: 0 },
      { name: 'الهانوفيل', cost: 0 },
    ],
  },
  {
    governorate: 'القليوبية',
    areas: [
      { name: 'بنها', cost: 0 },
      { name: 'شبرا الخيمة', cost: 0 },
      { name: 'قليوب', cost: 0 },
      { name: 'القناطر الخيرية', cost: 0 },
      { name: 'الخانكة', cost: 0 },
      { name: 'كفر شكر', cost: 0 },
      { name: 'طوخ', cost: 0 },
      { name: 'شبين القناطر', cost: 0 },
      { name: 'العبور', cost: 0 },
      { name: 'الخصوص', cost: 0 },
    ],
  },
  {
    governorate: 'الشرقية',
    areas: [
      { name: 'الزقازيق', cost: 0 },
      { name: 'العاشر من رمضان', cost: 0 },
      { name: 'بلبيس', cost: 0 },
      { name: 'منيا القمح', cost: 0 },
      { name: 'أبو حماد', cost: 0 },
      { name: 'أبو كبير', cost: 0 },
      { name: 'فاقوس', cost: 0 },
      { name: 'الحسينية', cost: 0 },
      { name: 'ديرب نجم', cost: 0 },
      { name: 'كفر صقر', cost: 0 },
      { name: 'أولاد صقر', cost: 0 },
      { name: 'ههيا', cost: 0 },
      { name: 'مشتول السوق', cost: 0 },
    ],
  },
  {
    governorate: 'الدقهلية',
    areas: [
      { name: 'المنصورة', cost: 0 },
      { name: 'طلخا', cost: 0 },
      { name: 'ميت غمر', cost: 0 },
      { name: 'دكرنس', cost: 0 },
      { name: 'أجا', cost: 0 },
      { name: 'السنبلاوين', cost: 0 },
      { name: 'المنزلة', cost: 0 },
      { name: 'شربين', cost: 0 },
      { name: 'بلقاس', cost: 0 },
      { name: 'المطرية', cost: 0 },
      { name: 'تمي الأمديد', cost: 0 },
      { name: 'الجمالية', cost: 0 },
      { name: 'منية النصر', cost: 0 },
      { name: 'نبروه', cost: 0 },
    ],
  },
  {
    governorate: 'الغربية',
    areas: [
      { name: 'طنطا', cost: 0 },
      { name: 'المحلة الكبرى', cost: 0 },
      { name: 'كفر الزيات', cost: 0 },
      { name: 'زفتى', cost: 0 },
      { name: 'السنطة', cost: 0 },
      { name: 'بسيون', cost: 0 },
      { name: 'قطور', cost: 0 },
      { name: 'سمنود', cost: 0 },
    ],
  },
  {
    governorate: 'المنوفية',
    areas: [
      { name: 'شبين الكوم', cost: 0 },
      { name: 'مدينة السادات', cost: 0 },
      { name: 'منوف', cost: 0 },
      { name: 'أشمون', cost: 0 },
      { name: 'الباجور', cost: 0 },
      { name: 'قويسنا', cost: 0 },
      { name: 'بركة السبع', cost: 0 },
      { name: 'تلا', cost: 0 },
      { name: 'الشهداء', cost: 0 },
    ],
  },
  {
    governorate: 'البحيرة',
    areas: [
      { name: 'دمنهور', cost: 0 },
      { name: 'كفر الدوار', cost: 0 },
      { name: 'رشيد', cost: 0 },
      { name: 'إدكو', cost: 0 },
      { name: 'أبو المطامير', cost: 0 },
      { name: 'حوش عيسى', cost: 0 },
      { name: 'شبراخيت', cost: 0 },
      { name: 'إيتاي البارود', cost: 0 },
      { name: 'المحمودية', cost: 0 },
      { name: 'الرحمانية', cost: 0 },
      { name: 'النوبارية', cost: 0 },
      { name: 'وادي النطرون', cost: 0 },
      { name: 'أبو حمص', cost: 0 },
      { name: 'الدلنجات', cost: 0 },
      { name: 'كوم حمادة', cost: 0 },
    ],
  },
  {
    governorate: 'كفر الشيخ',
    areas: [
      { name: 'كفر الشيخ', cost: 0 },
      { name: 'دسوق', cost: 0 },
      { name: 'فوه', cost: 0 },
      { name: 'مطوبس', cost: 0 },
      { name: 'بلطيم', cost: 0 },
      { name: 'الحامول', cost: 0 },
      { name: 'بيلا', cost: 0 },
      { name: 'سيدي سالم', cost: 0 },
      { name: 'الرياض', cost: 0 },
      { name: 'قلين', cost: 0 },
    ],
  },
  {
    governorate: 'دمياط',
    areas: [
      { name: 'دمياط', cost: 0 },
      { name: 'دمياط الجديدة', cost: 0 },
      { name: 'رأس البر', cost: 0 },
      { name: 'فارسكور', cost: 0 },
      { name: 'كفر سعد', cost: 0 },
      { name: 'الزرقا', cost: 0 },
      { name: 'كفر البطيخ', cost: 0 },
    ],
  },
  {
    governorate: 'بورسعيد',
    areas: [
      { name: 'حي الشرق', cost: 0 },
      { name: 'حي العرب', cost: 0 },
      { name: 'حي المناخ', cost: 0 },
      { name: 'حي الضواحي', cost: 0 },
      { name: 'حي الزهور', cost: 0 },
      { name: 'بورفؤاد', cost: 0 },
    ],
  },
  {
    governorate: 'الإسماعيلية',
    areas: [
      { name: 'الإسماعيلية', cost: 0 },
      { name: 'فايد', cost: 0 },
      { name: 'القنطرة شرق', cost: 0 },
      { name: 'القنطرة غرب', cost: 0 },
      { name: 'التل الكبير', cost: 0 },
      { name: 'أبو صوير', cost: 0 },
    ],
  },
  {
    governorate: 'السويس',
    areas: [
      { name: 'حي السويس', cost: 0 },
      { name: 'حي الأربعين', cost: 0 },
      { name: 'عتاقة', cost: 0 },
      { name: 'فيصل', cost: 0 },
      { name: 'الجناين', cost: 0 },
    ],
  },
  {
    governorate: 'الفيوم',
    areas: [
      { name: 'الفيوم', cost: 0 },
      { name: 'الفيوم الجديدة', cost: 0 },
      { name: 'إطسا', cost: 0 },
      { name: 'طامية', cost: 0 },
      { name: 'سنورس', cost: 0 },
      { name: 'أبشواي', cost: 0 },
      { name: 'يوسف الصديق', cost: 0 },
    ],
  },
  {
    governorate: 'بني سويف',
    areas: [
      { name: 'بني سويف', cost: 0 },
      { name: 'بني سويف الجديدة', cost: 0 },
      { name: 'الواسطى', cost: 0 },
      { name: 'ناصر', cost: 0 },
      { name: 'إهناسيا', cost: 0 },
      { name: 'ببا', cost: 0 },
      { name: 'سمسطا', cost: 0 },
    ],
  },
  {
    governorate: 'المنيا',
    areas: [
      { name: 'المنيا', cost: 0 },
      { name: 'المنيا الجديدة', cost: 0 },
      { name: 'ملوي', cost: 0 },
      { name: 'سمالوط', cost: 0 },
      { name: 'المغاغة', cost: 0 },
      { name: 'بني مزار', cost: 0 },
      { name: 'مطاي', cost: 0 },
      { name: 'أبو قرقاص', cost: 0 },
      { name: 'ديرمواس', cost: 0 },
      { name: 'العدوة', cost: 0 },
    ],
  },
  {
    governorate: 'أسيوط',
    areas: [
      { name: 'أسيوط', cost: 0 },
      { name: 'أسيوط الجديدة', cost: 0 },
      { name: 'ديروط', cost: 0 },
      { name: 'القوصية', cost: 0 },
      { name: 'منفلوط', cost: 0 },
      { name: 'أبنوب', cost: 0 },
      { name: 'أبو تيج', cost: 0 },
      { name: 'الغنايم', cost: 0 },
      { name: 'ساحل سليم', cost: 0 },
      { name: 'البداري', cost: 0 },
      { name: 'صدفا', cost: 0 },
    ],
  },
  {
    governorate: 'سوهاج',
    areas: [
      { name: 'سوهاج', cost: 0 },
      { name: 'سوهاج الجديدة', cost: 0 },
      { name: 'أخميم', cost: 0 },
      { name: 'طهطا', cost: 0 },
      { name: 'المراغة', cost: 0 },
      { name: 'جرجا', cost: 0 },
      { name: 'البلينا', cost: 0 },
      { name: 'المنشاة', cost: 0 },
      { name: 'دار السلام', cost: 0 },
      { name: 'جهينة', cost: 0 },
      { name: 'ساقلتة', cost: 0 },
      { name: 'طما', cost: 0 },
    ],
  },
  {
    governorate: 'قنا',
    areas: [
      { name: 'قنا', cost: 0 },
      { name: 'قنا الجديدة', cost: 0 },
      { name: 'نجع حمادي', cost: 0 },
      { name: 'دشنا', cost: 0 },
      { name: 'قوص', cost: 0 },
      { name: 'فرشوط', cost: 0 },
      { name: 'نقادة', cost: 0 },
      { name: 'أبو تشت', cost: 0 },
      { name: 'الوقف', cost: 0 },
    ],
  },
  {
    governorate: 'الأقصر',
    areas: [
      { name: 'الأقصر', cost: 0 },
      { name: 'الأقصر الجديدة', cost: 0 },
      { name: 'إسنا', cost: 0 },
      { name: 'أرمنت', cost: 0 },
      { name: 'الطود', cost: 0 },
      { name: 'القرنة', cost: 0 },
      { name: 'البياضية', cost: 0 },
    ],
  },
  {
    governorate: 'أسوان',
    areas: [
      { name: 'أسوان', cost: 0 },
      { name: 'أسوان الجديدة', cost: 0 },
      { name: 'كوم أمبو', cost: 0 },
      { name: 'دراو', cost: 0 },
      { name: 'إدفو', cost: 0 },
      { name: 'نصر النوبة', cost: 0 },
      { name: 'أبو سمبل', cost: 0 },
    ],
  },
  {
    governorate: 'البحر الأحمر',
    areas: [
      { name: 'الغردقة', cost: 0 },
      { name: 'سفاجا', cost: 0 },
      { name: 'القصير', cost: 0 },
      { name: 'مرسى علم', cost: 0 },
      { name: 'رأس غارب', cost: 0 },
      { name: 'الشلاتين', cost: 0 },
      { name: 'حلايب', cost: 0 },
    ],
  },
  {
    governorate: 'مطروح',
    areas: [
      { name: 'مرسى مطروح', cost: 0 },
      { name: 'الحمام', cost: 0 },
      { name: 'العلمين', cost: 0 },
      { name: 'الضبعة', cost: 0 },
      { name: 'سيدي عبد الرحمن', cost: 0 },
      { name: 'سيوة', cost: 0 },
      { name: 'النجيلة', cost: 0 },
      { name: 'براني', cost: 0 },
      { name: 'السلوم', cost: 0 },
    ],
  },
  {
    governorate: 'شمال سيناء',
    areas: [
      { name: 'العريش', cost: 0 },
      { name: 'بئر العبد', cost: 0 },
      { name: 'الشيخ زويد', cost: 0 },
      { name: 'رفح', cost: 0 },
      { name: 'الحسنة', cost: 0 },
      { name: 'نخل', cost: 0 },
    ],
  },
  {
    governorate: 'جنوب سيناء',
    areas: [
      { name: 'شرم الشيخ', cost: 0 },
      { name: 'دهب', cost: 0 },
      { name: 'نويبع', cost: 0 },
      { name: 'طابا', cost: 0 },
      { name: 'سانت كاترين', cost: 0 },
      { name: 'الطور', cost: 0 },
      { name: 'رأس سدر', cost: 0 },
      { name: 'أبو زنيمة', cost: 0 },
    ],
  },
  {
    governorate: 'الوادي الجديد',
    areas: [
      { name: 'الخارجة', cost: 0 },
      { name: 'الداخلة', cost: 0 },
      { name: 'الفرافرة', cost: 0 },
      { name: 'باريس', cost: 0 },
      { name: 'بلاط', cost: 0 },
    ],
  },
];

async function seedShipping() {
  try {
    await connectDB();
    console.log('Connected to DB');

    // Only seed if no zones exist
    const count = await ShippingZone.countDocuments();
    if (count > 0) {
      console.log(`Already have ${count} shipping zones. Skipping seed.`);
      process.exit(0);
    }

    await ShippingZone.insertMany(egyptGovernorates);
    console.log(`Seeded ${egyptGovernorates.length} governorates with their areas (costs set to 0)`);
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
}

seedShipping();
